version: '2.2'
services:
  zookeeper:
    image: scioquiver/zookeeper:default
    container_name: Zookeeper
    ports:
      - 2181:2181
    environment:
      - ${host}
  elasticsearch:
    image: scioquiver/elasticsearch:ontologies
    container_name: Elastic
    ports:
      - 9200:9200
    environment:
      - ${host}
    network_mode: "host"
  mongo:
    image: mongo:3.4.19
    container_name: Mongo
    ports:
      - 27017:27017
    environment:
      - ${host}
    network_mode: "host"
  piiEngine:
    image: sciogardian/piiengine:0_5.camel
    container_name: piiEngineSfs
    command: ${host}
    network_mode: "host"
    volumes:
      - /sfs:/sfs
  piiUserInterface:
    image: sciogardian/piiuserinterface:0_5.play
    container_name: piiUiSfs
    ports:
      - 9000:9000
      - 9443:9443
    environment:
      - ${host}
    command: ${host}
    depends_on: 
      - elasticsearch
      - mongo
      - piiEngine
      - kafka
  kafka:
    image: scioquiver/kafka:default
    container_name: Kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${host}
      KAFKA_ZOOKEEPER_CONNECT: ${host}:2181
    network_mode: "host"
    depends_on: 
      - zookeeper
